import { MigrationInterface, QueryRunner } from "typeorm";

export class AddDeletedAtToTickets1767030751624 implements MigrationInterface {
    name = 'AddDeletedAtToTickets1767030751624'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "niveis_atendimento" DROP CONSTRAINT "fk_nivel_empresa"`);
        await queryRunner.query(`ALTER TABLE "status_customizados" DROP CONSTRAINT "fk_status_empresa"`);
        await queryRunner.query(`ALTER TABLE "status_customizados" DROP CONSTRAINT "fk_status_nivel"`);
        await queryRunner.query(`ALTER TABLE "tipos_servico" DROP CONSTRAINT "fk_tipo_empresa"`);
        await queryRunner.query(`ALTER TABLE "atendimento_tickets" DROP CONSTRAINT "fk_ticket_tipo_servico"`);
        await queryRunner.query(`ALTER TABLE "atendimento_tickets" DROP CONSTRAINT "fk_ticket_status_customizado"`);
        await queryRunner.query(`ALTER TABLE "atendimento_tickets" DROP CONSTRAINT "fk_ticket_nivel_atendimento"`);
        await queryRunner.query(`ALTER TABLE "faturas" DROP CONSTRAINT "FK_644bf709a39af5c760b98e56a06"`);
        await queryRunner.query(`ALTER TABLE "atendimento_templates" DROP CONSTRAINT "fk_atendimento_templates_empresa"`);
        await queryRunner.query(`DROP INDEX "public"."idx_niveis_empresa_ordem"`);
        await queryRunner.query(`DROP INDEX "public"."idx_status_empresa_nivel_ordem"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tipos_empresa_ordem"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tickets_cliente_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tickets_tipo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tickets_responsavel_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tickets_autor_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tickets_data_vencimento"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tickets_nivel_atendimento"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tickets_status_customizado"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tickets_tipo_servico"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67862e1af92d16dfa50f4e9d18"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1162d4fe194d2e32a9ecf6ccb4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0d57c7b5bde732ac3d3ed3558"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_139d3276e0a299deacb53a557d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60cf6cd7b6a1b7298af56b056d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c74f605d546764c24c0d9451f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a4c04e78810691f77a6c4dd8e6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0741e7b51d90755844ae04d67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_450c254ac416c5207f90573259"`);
        await queryRunner.query(`DROP INDEX "public"."idx_atendimento_templates_empresa"`);
        await queryRunner.query(`DROP INDEX "public"."idx_atendimento_templates_atalho"`);
        await queryRunner.query(`DROP INDEX "public"."idx_atendimento_mensagens_whatsapp_message_id"`);
        await queryRunner.query(`ALTER TABLE "niveis_atendimento" DROP CONSTRAINT "uq_nivel_codigo_empresa"`);
        await queryRunner.query(`ALTER TABLE "faturas" DROP COLUMN "atualizadoPor"`);
        await queryRunner.query(`ALTER TABLE "faturas" DROP COLUMN "criadoPor"`);
        await queryRunner.query(`ALTER TABLE "faturas" DROP COLUMN "empresa_id"`);
        await queryRunner.query(`ALTER TABLE "atendimento_templates" DROP COLUMN "anexos"`);
        await queryRunner.query(`ALTER TABLE "atendimento_templates" DROP COLUMN "variaveis"`);
        await queryRunner.query(`ALTER TABLE "atendimento_templates" DROP COLUMN "total_usos"`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_configs" DROP COLUMN "mapeamento_status"`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_configs" DROP COLUMN "mapeamento_trackers"`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_configs" DROP COLUMN "mapeamento_prioridade"`);
        await queryRunner.query(`ALTER TABLE "atendimento_mensagens" DROP COLUMN "status_whatsapp"`);
        await queryRunner.query(`ALTER TABLE "atendimento_mensagens" DROP COLUMN "status_atualizado_em"`);
        await queryRunner.query(`ALTER TABLE "atendimento_mensagens" DROP COLUMN "whatsapp_message_id"`);
        await queryRunner.query(`ALTER TABLE "faturas" ADD "empresa_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "faturas" ADD "criadoPor" uuid`);
        await queryRunner.query(`ALTER TABLE "faturas" ADD "atualizadoPor" uuid`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_configs" ADD "mapeamentoTrackers" jsonb`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_configs" ADD "mapeamentoStatus" jsonb`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_configs" ADD "mapeamentoPrioridade" jsonb`);
        await queryRunner.query(`ALTER TABLE "niveis_atendimento" ALTER COLUMN "ativo" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "niveis_atendimento" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "niveis_atendimento" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "status_customizados" ALTER COLUMN "finalizador" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "status_customizados" ALTER COLUMN "ativo" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "status_customizados" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "status_customizados" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipos_servico" ALTER COLUMN "ordem" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipos_servico" ALTER COLUMN "ativo" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipos_servico" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipos_servico" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "configuracoes_gateway_pagamento" ALTER COLUMN "credenciais" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "configuracoes_gateway_pagamento" ALTER COLUMN "metodos_permitidos" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "faturas" DROP CONSTRAINT "FK_9b8490bce74e62adb498b5ccbb6"`);
        await queryRunner.query(`ALTER TABLE "faturas" ALTER COLUMN "contratoId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "faturas" ALTER COLUMN "valorTotal" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "faturas" ALTER COLUMN "valorPago" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "faturas" ALTER COLUMN "valorDesconto" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "faturas" ALTER COLUMN "valorJuros" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "faturas" ALTER COLUMN "valorMulta" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "transacoes_gateway_pagamento" ALTER COLUMN "payload_envio" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "transacoes_gateway_pagamento" ALTER COLUMN "payload_resposta" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "atendimento_templates" ALTER COLUMN "ativo" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "atendimento_templates" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "atendimento_templates" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_integrations" DROP COLUMN "status_sincronizacao"`);
        await queryRunner.query(`CREATE TYPE "public"."atendimento_redmine_integrations_status_sincronizacao_enum" AS ENUM('pendente', 'sincronizado', 'erro', 'conflito')`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_integrations" ADD "status_sincronizacao" "public"."atendimento_redmine_integrations_status_sincronizacao_enum" NOT NULL DEFAULT 'pendente'`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_integrations" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_integrations" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_configs" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_configs" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_9d3fdd83dc8c71a2f358b3d03c" ON "niveis_atendimento" ("empresa_id", "ordem") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_969535a8d6e34b39b3d46dc1a1" ON "niveis_atendimento" ("empresa_id", "codigo") `);
        await queryRunner.query(`CREATE INDEX "IDX_857b3d028786e16a768578b1ee" ON "status_customizados" ("empresa_id", "nivel_id", "ordem") `);
        await queryRunner.query(`CREATE INDEX "IDX_1dfc2cb0aefa52a6c35973e317" ON "tipos_servico" ("empresa_id", "ordem") `);
        await queryRunner.query(`CREATE INDEX "IDX_67862e1af92d16dfa50f4e9d18" ON "faturas" ("clienteId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1162d4fe194d2e32a9ecf6ccb4" ON "faturas" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c0d57c7b5bde732ac3d3ed3558" ON "faturas" ("dataEmissao") `);
        await queryRunner.query(`CREATE INDEX "IDX_139d3276e0a299deacb53a557d" ON "faturas" ("dataVencimento") `);
        await queryRunner.query(`CREATE INDEX "IDX_60cf6cd7b6a1b7298af56b056d" ON "faturas" ("ativo") `);
        await queryRunner.query(`CREATE INDEX "IDX_c74f605d546764c24c0d9451f0" ON "faturas" ("createdAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a4c04e78810691f77a6c4dd8e6" ON "faturas" ("numero") `);
        await queryRunner.query(`CREATE INDEX "IDX_e0741e7b51d90755844ae04d67" ON "faturas" ("dataVencimento", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_450c254ac416c5207f90573259" ON "faturas" ("clienteId", "status") `);
        await queryRunner.query(`ALTER TABLE "niveis_atendimento" ADD CONSTRAINT "FK_c8b2bda38faa618587eace44f57" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "status_customizados" ADD CONSTRAINT "FK_a0f1a5d458739544b0e12557b46" FOREIGN KEY ("nivel_id") REFERENCES "niveis_atendimento"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "status_customizados" ADD CONSTRAINT "FK_81a5649758f6d27d069675ac2f2" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipos_servico" ADD CONSTRAINT "FK_212fda94a501a046aa98f9fbe5f" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "atendimento_tickets" ADD CONSTRAINT "FK_d4f2767b2d70b1af8648ad4f9e1" FOREIGN KEY ("nivel_atendimento_id") REFERENCES "niveis_atendimento"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "atendimento_tickets" ADD CONSTRAINT "FK_4f398ec3cd6e8e9b1473e7b7c35" FOREIGN KEY ("status_customizado_id") REFERENCES "status_customizados"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "atendimento_tickets" ADD CONSTRAINT "FK_cb3701192e424cc0ac12c857a1f" FOREIGN KEY ("tipo_servico_id") REFERENCES "tipos_servico"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "atendimento_tickets" ADD CONSTRAINT "FK_be5569167a366c9817cd932adc2" FOREIGN KEY ("responsavel_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "atendimento_tickets" ADD CONSTRAINT "FK_fe6b43044d81d30aee1159e891b" FOREIGN KEY ("autor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "faturas" ADD CONSTRAINT "FK_9b8490bce74e62adb498b5ccbb6" FOREIGN KEY ("contratoId") REFERENCES "contratos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "faturas" ADD CONSTRAINT "FK_644bf709a39af5c760b98e56a06" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "atendimento_templates" ADD CONSTRAINT "FK_b548380f6348e2c89156fcc35cb" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "atendimento_templates" DROP CONSTRAINT "FK_b548380f6348e2c89156fcc35cb"`);
        await queryRunner.query(`ALTER TABLE "faturas" DROP CONSTRAINT "FK_644bf709a39af5c760b98e56a06"`);
        await queryRunner.query(`ALTER TABLE "faturas" DROP CONSTRAINT "FK_9b8490bce74e62adb498b5ccbb6"`);
        await queryRunner.query(`ALTER TABLE "atendimento_tickets" DROP CONSTRAINT "FK_fe6b43044d81d30aee1159e891b"`);
        await queryRunner.query(`ALTER TABLE "atendimento_tickets" DROP CONSTRAINT "FK_be5569167a366c9817cd932adc2"`);
        await queryRunner.query(`ALTER TABLE "atendimento_tickets" DROP CONSTRAINT "FK_cb3701192e424cc0ac12c857a1f"`);
        await queryRunner.query(`ALTER TABLE "atendimento_tickets" DROP CONSTRAINT "FK_4f398ec3cd6e8e9b1473e7b7c35"`);
        await queryRunner.query(`ALTER TABLE "atendimento_tickets" DROP CONSTRAINT "FK_d4f2767b2d70b1af8648ad4f9e1"`);
        await queryRunner.query(`ALTER TABLE "tipos_servico" DROP CONSTRAINT "FK_212fda94a501a046aa98f9fbe5f"`);
        await queryRunner.query(`ALTER TABLE "status_customizados" DROP CONSTRAINT "FK_81a5649758f6d27d069675ac2f2"`);
        await queryRunner.query(`ALTER TABLE "status_customizados" DROP CONSTRAINT "FK_a0f1a5d458739544b0e12557b46"`);
        await queryRunner.query(`ALTER TABLE "niveis_atendimento" DROP CONSTRAINT "FK_c8b2bda38faa618587eace44f57"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_450c254ac416c5207f90573259"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0741e7b51d90755844ae04d67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a4c04e78810691f77a6c4dd8e6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c74f605d546764c24c0d9451f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60cf6cd7b6a1b7298af56b056d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_139d3276e0a299deacb53a557d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0d57c7b5bde732ac3d3ed3558"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1162d4fe194d2e32a9ecf6ccb4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67862e1af92d16dfa50f4e9d18"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1dfc2cb0aefa52a6c35973e317"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_857b3d028786e16a768578b1ee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_969535a8d6e34b39b3d46dc1a1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9d3fdd83dc8c71a2f358b3d03c"`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_configs" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_configs" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_integrations" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_integrations" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_integrations" DROP COLUMN "status_sincronizacao"`);
        await queryRunner.query(`DROP TYPE "public"."atendimento_redmine_integrations_status_sincronizacao_enum"`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_integrations" ADD "status_sincronizacao" character varying(20) NOT NULL DEFAULT 'pendente'`);
        await queryRunner.query(`ALTER TABLE "atendimento_templates" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "atendimento_templates" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "atendimento_templates" ALTER COLUMN "ativo" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transacoes_gateway_pagamento" ALTER COLUMN "payload_resposta" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "transacoes_gateway_pagamento" ALTER COLUMN "payload_envio" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "faturas" ALTER COLUMN "valorMulta" TYPE numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "faturas" ALTER COLUMN "valorJuros" TYPE numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "faturas" ALTER COLUMN "valorDesconto" TYPE numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "faturas" ALTER COLUMN "valorPago" TYPE numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "faturas" ALTER COLUMN "valorTotal" TYPE numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "faturas" ALTER COLUMN "contratoId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "faturas" ADD CONSTRAINT "FK_9b8490bce74e62adb498b5ccbb6" FOREIGN KEY ("contratoId") REFERENCES "contratos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "configuracoes_gateway_pagamento" ALTER COLUMN "metodos_permitidos" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "configuracoes_gateway_pagamento" ALTER COLUMN "credenciais" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "tipos_servico" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipos_servico" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipos_servico" ALTER COLUMN "ativo" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipos_servico" ALTER COLUMN "ordem" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "status_customizados" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "status_customizados" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "status_customizados" ALTER COLUMN "ativo" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "status_customizados" ALTER COLUMN "finalizador" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "niveis_atendimento" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "niveis_atendimento" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "niveis_atendimento" ALTER COLUMN "ativo" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_configs" DROP COLUMN "mapeamentoPrioridade"`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_configs" DROP COLUMN "mapeamentoStatus"`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_configs" DROP COLUMN "mapeamentoTrackers"`);
        await queryRunner.query(`ALTER TABLE "faturas" DROP COLUMN "atualizadoPor"`);
        await queryRunner.query(`ALTER TABLE "faturas" DROP COLUMN "criadoPor"`);
        await queryRunner.query(`ALTER TABLE "faturas" DROP COLUMN "empresa_id"`);
        await queryRunner.query(`ALTER TABLE "atendimento_mensagens" ADD "whatsapp_message_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "atendimento_mensagens" ADD "status_atualizado_em" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "atendimento_mensagens" ADD "status_whatsapp" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_configs" ADD "mapeamento_prioridade" jsonb`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_configs" ADD "mapeamento_trackers" jsonb`);
        await queryRunner.query(`ALTER TABLE "atendimento_redmine_configs" ADD "mapeamento_status" jsonb`);
        await queryRunner.query(`ALTER TABLE "atendimento_templates" ADD "total_usos" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "atendimento_templates" ADD "variaveis" text array`);
        await queryRunner.query(`ALTER TABLE "atendimento_templates" ADD "anexos" jsonb`);
        await queryRunner.query(`ALTER TABLE "faturas" ADD "empresa_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "faturas" ADD "criadoPor" uuid`);
        await queryRunner.query(`ALTER TABLE "faturas" ADD "atualizadoPor" uuid`);
        await queryRunner.query(`ALTER TABLE "niveis_atendimento" ADD CONSTRAINT "uq_nivel_codigo_empresa" UNIQUE ("codigo", "empresa_id")`);
        await queryRunner.query(`CREATE INDEX "idx_atendimento_mensagens_whatsapp_message_id" ON "atendimento_mensagens" ("whatsapp_message_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_atendimento_templates_atalho" ON "atendimento_templates" ("empresa_id", "atalho") `);
        await queryRunner.query(`CREATE INDEX "idx_atendimento_templates_empresa" ON "atendimento_templates" ("empresa_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_450c254ac416c5207f90573259" ON "faturas" ("clienteId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e0741e7b51d90755844ae04d67" ON "faturas" ("dataVencimento", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a4c04e78810691f77a6c4dd8e6" ON "faturas" ("numero") `);
        await queryRunner.query(`CREATE INDEX "IDX_c74f605d546764c24c0d9451f0" ON "faturas" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_60cf6cd7b6a1b7298af56b056d" ON "faturas" ("ativo") `);
        await queryRunner.query(`CREATE INDEX "IDX_139d3276e0a299deacb53a557d" ON "faturas" ("dataVencimento") `);
        await queryRunner.query(`CREATE INDEX "IDX_c0d57c7b5bde732ac3d3ed3558" ON "faturas" ("dataEmissao") `);
        await queryRunner.query(`CREATE INDEX "IDX_1162d4fe194d2e32a9ecf6ccb4" ON "faturas" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_67862e1af92d16dfa50f4e9d18" ON "faturas" ("clienteId") `);
        await queryRunner.query(`CREATE INDEX "idx_tickets_tipo_servico" ON "atendimento_tickets" ("tipo_servico_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tickets_status_customizado" ON "atendimento_tickets" ("status_customizado_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tickets_nivel_atendimento" ON "atendimento_tickets" ("nivel_atendimento_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tickets_data_vencimento" ON "atendimento_tickets" ("data_vencimento") `);
        await queryRunner.query(`CREATE INDEX "idx_tickets_autor_id" ON "atendimento_tickets" ("autor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tickets_responsavel_id" ON "atendimento_tickets" ("responsavel_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tickets_tipo" ON "atendimento_tickets" ("tipo") `);
        await queryRunner.query(`CREATE INDEX "idx_tickets_cliente_id" ON "atendimento_tickets" ("cliente_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tipos_empresa_ordem" ON "tipos_servico" ("ordem", "empresa_id") `);
        await queryRunner.query(`CREATE INDEX "idx_status_empresa_nivel_ordem" ON "status_customizados" ("nivel_id", "ordem", "empresa_id") `);
        await queryRunner.query(`CREATE INDEX "idx_niveis_empresa_ordem" ON "niveis_atendimento" ("ordem", "empresa_id") `);
        await queryRunner.query(`ALTER TABLE "atendimento_templates" ADD CONSTRAINT "fk_atendimento_templates_empresa" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "faturas" ADD CONSTRAINT "FK_644bf709a39af5c760b98e56a06" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "atendimento_tickets" ADD CONSTRAINT "fk_ticket_nivel_atendimento" FOREIGN KEY ("nivel_atendimento_id") REFERENCES "niveis_atendimento"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "atendimento_tickets" ADD CONSTRAINT "fk_ticket_status_customizado" FOREIGN KEY ("status_customizado_id") REFERENCES "status_customizados"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "atendimento_tickets" ADD CONSTRAINT "fk_ticket_tipo_servico" FOREIGN KEY ("tipo_servico_id") REFERENCES "tipos_servico"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipos_servico" ADD CONSTRAINT "fk_tipo_empresa" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "status_customizados" ADD CONSTRAINT "fk_status_nivel" FOREIGN KEY ("nivel_id") REFERENCES "niveis_atendimento"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "status_customizados" ADD CONSTRAINT "fk_status_empresa" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "niveis_atendimento" ADD CONSTRAINT "fk_nivel_empresa" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
