import { Contato } from './contatosService';

export const contatosMock: Contato[] = [
  {
    id: '1',
    nome: 'João Silva',
    email: 'joao.silva@empresa.com.br',
    telefone: '(11) 99999-9999',
    empresa: 'Tech Solutions Ltda',
    cargo: 'CEO',
    status: 'cliente',
    tipo: 'cliente',
    fonte: 'LinkedIn',
    proprietario: 'Maria Santos',
    data_criacao: '2024-01-15T10:00:00Z',
    data_ultima_interacao: '2024-01-20T14:30:00Z',
    data_nascimento: '1985-03-22',
    endereco: {
      rua: 'Rua das Flores, 123, Sala 45',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01234-567',
      pais: 'Brasil',
    },
    redes_sociais: {
      linkedin: 'https://linkedin.com/in/joaosilva',
      twitter: 'https://twitter.com/joaosilva',
    },
    tags: ['Cliente VIP', 'Tecnologia', 'Tomador de Decisão'],
    pontuacao_lead: 95,
    valor_potencial: 150000,
    notas:
      'Cliente muito engajado, interessado em expandir o negócio. Possui budget aprovado para novos projetos.',
    anexos: [],
    atividades_recentes: 12,
    oportunidades_abertas: 2,
    vendas_realizadas: 3,
    valor_total_vendas: 450000,
    categoria: 'Tecnologia',
  },
  {
    id: '2',
    nome: 'Maria Oliveira',
    email: 'maria.oliveira@startup.com',
    telefone: '(11) 88888-8888',
    empresa: 'StartupX',
    cargo: 'CTO',
    status: 'prospecto',
    tipo: 'lead',
    fonte: 'Website',
    proprietario: 'Pedro Costa',
    data_criacao: '2024-01-18T08:00:00Z',
    data_ultima_interacao: '2024-01-19T16:45:00Z',
    data_nascimento: '1990-07-15',
    endereco: {
      rua: 'Av. Paulista, 1000, Conj. 2001',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01310-100',
      pais: 'Brasil',
    },
    redes_sociais: {
      linkedin: 'https://linkedin.com/in/mariaoliveira',
      twitter: 'https://twitter.com/mariaoliveira',
    },
    tags: ['Startup', 'Inovação', 'Hot Lead'],
    pontuacao_lead: 85,
    valor_potencial: 75000,
    notas: 'Demonstrou muito interesse no produto. Startup em crescimento com potencial de escala.',
    anexos: [],
    atividades_recentes: 8,
    oportunidades_abertas: 1,
    vendas_realizadas: 0,
    valor_total_vendas: 0,
    categoria: 'Startup',
  },
  {
    id: '3',
    nome: 'Carlos Santos',
    email: 'carlos.santos@industria.com.br',
    telefone: '(11) 77777-7777',
    empresa: 'Indústria Brasil S.A.',
    cargo: 'Diretor de TI',
    status: 'ativo',
    tipo: 'parceiro',
    fonte: 'Indicação',
    proprietario: 'Ana Silva',
    data_criacao: '2024-01-10T13:30:00Z',
    data_ultima_interacao: '2024-01-22T11:20:00Z',
    endereco: {
      rua: 'Rua Industrial, 500',
      cidade: 'São Bernardo do Campo',
      estado: 'SP',
      cep: '09750-000',
      pais: 'Brasil',
    },
    redes_sociais: {
      linkedin: 'https://linkedin.com/in/carlossantos',
    },
    tags: ['Indústria', 'Parceiro Estratégico', 'Volume Alto'],
    pontuacao_lead: 70,
    valor_potencial: 300000,
    notas:
      'Parceiro de longa data. Sempre busca soluções inovadoras para modernizar a infraestrutura.',
    anexos: [],
    atividades_recentes: 15,
    oportunidades_abertas: 3,
    vendas_realizadas: 5,
    valor_total_vendas: 1200000,
    categoria: 'Indústria',
  },
  {
    id: '4',
    nome: 'Ana Costa',
    email: 'ana.costa@consultoria.com',
    telefone: '(11) 66666-6666',
    empresa: 'Costa Consultoria',
    cargo: 'Sócia-Fundadora',
    status: 'cliente',
    tipo: 'cliente',
    fonte: 'Networking',
    proprietario: 'Lucas Oliveira',
    data_criacao: '2024-01-05T09:15:00Z',
    data_ultima_interacao: '2024-01-21T15:00:00Z',
    data_nascimento: '1982-11-30',
    endereco: {
      rua: 'Rua Augusta, 2500, Sala 1205',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01412-100',
      pais: 'Brasil',
    },
    redes_sociais: {
      linkedin: 'https://linkedin.com/in/anacosta',
      instagram: 'https://instagram.com/anacostaconsultoria',
    },
    tags: ['Consultoria', 'Networking', 'Influenciadora'],
    pontuacao_lead: 88,
    valor_potencial: 120000,
    notas: 'Excelente relacionamento. Sempre indica novos clientes. Consultoria de alto nível.',
    anexos: [],
    atividades_recentes: 10,
    oportunidades_abertas: 1,
    vendas_realizadas: 4,
    valor_total_vendas: 380000,
    categoria: 'Consultoria',
  },
  {
    id: '5',
    nome: 'Roberto Lima',
    email: 'roberto.lima@varejo.com.br',
    telefone: '(11) 55555-5555',
    empresa: 'MegaVarejo',
    cargo: 'Gerente de Operações',
    status: 'prospecto',
    tipo: 'lead',
    fonte: 'Google Ads',
    proprietario: 'Carla Santos',
    data_criacao: '2024-01-20T11:45:00Z',
    data_ultima_interacao: '2024-01-22T09:30:00Z',
    endereco: {
      rua: 'Av. Brasil, 3000',
      cidade: 'Rio de Janeiro',
      estado: 'RJ',
      cep: '21040-020',
      pais: 'Brasil',
    },
    redes_sociais: {
      linkedin: 'https://linkedin.com/in/robertolima',
    },
    tags: ['Varejo', 'Grande Empresa', 'Orçamento Aprovado'],
    pontuacao_lead: 75,
    valor_potencial: 200000,
    notas: 'Grande interesse em automação de processos. Empresa com múltiplas unidades.',
    anexos: [],
    atividades_recentes: 6,
    oportunidades_abertas: 2,
    vendas_realizadas: 0,
    valor_total_vendas: 0,
    categoria: 'Varejo',
  },
  {
    id: '6',
    nome: 'Fernanda Pereira',
    email: 'fernanda.pereira@educacao.org',
    telefone: '(11) 44444-4444',
    empresa: 'Instituto Educacional',
    cargo: 'Diretora Acadêmica',
    status: 'ativo',
    tipo: 'lead',
    fonte: 'Feira/Evento',
    proprietario: 'Roberto Lima',
    data_criacao: '2024-01-12T14:20:00Z',
    data_ultima_interacao: '2024-01-20T10:15:00Z',
    data_nascimento: '1978-09-08',
    endereco: {
      rua: 'Rua da Educação, 200',
      cidade: 'Campinas',
      estado: 'SP',
      cep: '13010-111',
      pais: 'Brasil',
    },
    redes_sociais: {
      linkedin: 'https://linkedin.com/in/fernandapereira',
      facebook: 'https://facebook.com/fernanda.pereira',
    },
    tags: ['Educação', 'Terceiro Setor', 'Inovação Educacional'],
    pontuacao_lead: 60,
    valor_potencial: 80000,
    notas: 'Muito interessada em tecnologias educacionais. Instituição em expansão.',
    anexos: [],
    atividades_recentes: 7,
    oportunidades_abertas: 1,
    vendas_realizadas: 1,
    valor_total_vendas: 65000,
    categoria: 'Educação',
  },
];
